- name: Delete the nvm script if exist
  file:
    path: /tmp/nvm.sh
    state: absent

- name: Download nvm install script. FIX hard code version number. FIX after install script
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh
    dest: /tmp/nvm.sh
    mode: 0755
  
- name: Execute the install script
  shell: /tmp/nvm.sh

- name: Delete the nvm script after complete
  file:
    path: /tmp/nvm.sh
    state: absent