---
- hosts: 127.0.0.1
  tasks:
  - name: Ansible apt with_items example
    ansible.builtin.apt:
      name: 
        - 'gnome-mines'
        - 'gnome-sudoku'
        - 'libreoffice'
        - 'parole'
        - 'ristretto'
        - 'sgt-puzzles'
        - 'transmission-common'
        - 'transmission-gtk'
        - 'xfburn'
      update_cache: true
      state: absent
    become: yes