- name: Install some basic packages
  package:
    name:
      - apt-transport-https
      - curl
      - git
      - gpg 
      - htop
      - software-properties-common
      - vim
      - wget
    state: present
    update_cache: true
  become: yes

- name: Install a few extra packages
  package:
    name:
      - gnome-online-accounts
      - htop
      - keepassxc
      - libavcodec-extra
      - synaptic
    state: present
    update_cache: true
  become: yes