- name: Install some basic pacakge useful for the rest of the install process.
  ansible.builtin.package:
    name:
      - curl
      - git
      - gpg 
      - htop
      - net-tools 
      - vim
      - wget
    state: present
    update_cache: true
  become: yes
# net-tools for debian ipconfig.

- name: Install some extra packages
  ansible.builtin.package:
    name:
      - gnome-online-accounts
      - keepassxc
      - libavcodec-extra 
    state: present
    update_cache: true
  become: yes