- name: Install prereq packages for podman
  ansible.builtin.package:
    name: 
      - curl
      - wget
      - gnupg2
  become: yes

# - name: Add podman repo
#   apt_repository:
#     repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}"
#     state: present
#     update_cache: yes
#   become: yes

- name: Add podman repo
  shell: sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
  become: yes

- name: Get podman GPG key
  apt_key: 
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_${VERSION_ID}/Release.key -O- | apt-key add
    state: present
  become: yes

- name: Install podman
  ansible.builtin.package:
    name: 
      - podman
    update_cache: yes
    state: present
  become: yes