- name: Add resilio key
  apt_key:
    url: http://linux-packages.resilio.com/resilio-sync/key.asc
    state: present
  become: yes

- name: Add resilio repo
  apt_repository:
    repo: "deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free"
    state: present
    update_cache: yes
  become: yes

- name: Install resilio sync
  ansible.builtin.package:
    name:
      - software-properties-common
      - resilio-sync
    state: present
  become: yes

- name: Run Resilio script initialization. Creates a default configuration that you will modify.
  shell: /etc/resilio-sync/init_user_config.sh

- name: Create directory /etc/systemd/system/resilio-sync.service.d
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - /etc/systemd/system/resilio-sync.service.d
  become: yes

- name: Copy config to service directory
  template:
    src: resilio.conf.j2
    dest: /etc/systemd/system/resilio-sync.service.d/override.conf
  become: yes

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable service resilio and ensure it is not masked
  systemd:
    name: resilio-sync
    enabled: yes
  become: yes

- name: Reload service resilio-sync, in all cases
  systemd:
    name: resilio-sync
    state: restarted
  become: yes