---
# Call all other playboosk to setup my setup.
# Mostly just some ansible pratice.
- name: Run the other roles
  hosts: localhost
  roles:
    - initialPackages
    - timezone
    - dot
    - chrome
    - vscodeAPT
    - python
    - golang
    - git
    - docker-ce
