---
# Call all other playboosk to setup my setup.
# Mostly just some ansible pratice.
- name: Run the other roles
  hosts: localhost
  roles:
    - initial_packages
    - gnome_accounts
    - gnome_settings
    - timezone
    - dot
    - chrome
    - python
    - vscode_apt
    - git
    - docker_ce
    - mise
