- name: Install python
  ansible.builtin.package:
    name:
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
    state: present
  become: yes

# Probably use venv
# - name: Install python pipenv
#   shell: pip3 install --user pipenv

# - name: Create symbolic link for python that reference python3. Remove if you need both 2 and 3 or they ever change python3 to python.
#   file:
#     src: "/usr/bin/python3"
#     dest: "/usr/bin/python"
#     state: link
#   become: yes