- name: Install python
  package:
    name:
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
  become: yes

- name: Install python pipenv
  shell: pip3 install --user pipenv