- name: Add an APT signing key from MSFT
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install VSCode
  package:
    name:
      - apt-transport-https
      - code
    state: present
    update_cache: true
  become: yes
