- name: Install packages need to compile the vbox guest additions.
  package:
    name:
      - "linux-headers-{{ ansible_kernel }}"
      - build-essential
      - dkms
      - gcc
    state: present
  become: yes