- name: Install prereq packages for podman
  ansible.builtin.package:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  become: yes

- name: Get docker GPG key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add docker repo. User specifies UBUNTU_CODE_NAME
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{code_name}} stable"
    state: present
    update_cache: yes
  when: code_name != ""
  become: yes

- name: Add docker repo. Fallback to safe repo since UBUNTU_CODE_NAME was not specified
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{safe_code_name}} stable"
    state: present
    update_cache: yes
  when: code_name == ""
  become: yes

- name: Install docker and docker compose
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present
  become: yes

# TODO: Probably add a dependency check to see if docker exist before doing anything.
# I wonder if this will just fail if docker not install. Then no checking is really needed..

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Add current user to docker group
  user:
    name: "{{ansible_env.USER}}"
    groups: docker
    append: yes
  become: yes

# - name: safecode
#   debug:
#     msg: "{{safe_code_name}}"
#   when: code_name == ""